// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBg2yiq5dcju7TKzWWrnKKo6O-T7T3nvbk',
    appId: '1:943215972929:web:14eb465c2af714cbd62cc0',
    messagingSenderId: '943215972929',
    projectId: 'lab-project-66e5a',
    authDomain: 'lab-project-66e5a.firebaseapp.com',
    storageBucket: 'lab-project-66e5a.firebasestorage.app',
    measurementId: 'G-FGJEZQVB1Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmpwpYhMFZqLpzrrbjj5ZvHZvcYbABjxQ',
    appId: '1:943215972929:android:2bcef5964bed6838d62cc0',
    messagingSenderId: '943215972929',
    projectId: 'lab-project-66e5a',
    storageBucket: 'lab-project-66e5a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmPoNi5axUqtJQP8m4cfIZ0MySuywWmN0',
    appId: '1:943215972929:ios:2a660a1f5413bbdfd62cc0',
    messagingSenderId: '943215972929',
    projectId: 'lab-project-66e5a',
    storageBucket: 'lab-project-66e5a.firebasestorage.app',
    iosBundleId: 'com.radian.labAssignmentAdmin',
  );
}
